name: Compile Shader
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download MaterialBinTool
        run: |
          wget https://github.com -O MaterialBinTool.jar

      - name: Compile to material.bin
        run: |
          # Perintah resmi MaterialBinTool untuk meng-compile langsung dari config.json di luar folder
          java -jar MaterialBinTool.jar -c config.json

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: shader-material-bin
          path: |
            **/*.material.bin
