name: Compile Shader
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download MaterialBinTool and Base Data
        run: |
          # Mengunduh Compiler Utama
          wget https://github.com -O MaterialBinTool.jar
          
          # Mengunduh Data Struktur Shader Esensial agar Java tidak crash
          wget https://githubusercontent.com
          wget https://githubusercontent.com

      - name: Compile to material.bin
        run: |
          # Perintah resmi kompilasi mandiri dari config.json
          java -jar MaterialBinTool.jar -c config.json
        continue-on-error: true

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: shader-material-bin
          path: |
            **/*.material.bin
